# Generated by Django 4.0.6 on 2022-11-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
