# Generated by Django 4.0.6 on 2022-11-18 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0003_rename_text_question_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="text",
            new_name="answer",
        ),
    ]
