# Generated by Django 4.0.6 on 2022-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_rename_text_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='attempt_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_answer',
            field=models.TextField(null=True),
        ),
    ]
