# Generated by Django 4.0.6 on 2022-07-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_questionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.ManyToManyField(to='shared_models.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
