# Generated by Django 4.0.6 on 2022-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_quizstatistics_subject_topic_remove_tag_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='question',
        ),
        migrations.AddField(
            model_name='topic',
            name='question',
            field=models.ManyToManyField(to='shared_models.question'),
        ),
    ]
