# Generated by Django 4.0.6 on 2022-07-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0006_subject_topic_delete_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared_models.subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topics",
            field=models.ManyToManyField(to="shared_models.topic"),
        ),
    ]
