# Generated by Django 4.0.6 on 2023-01-14 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_rename_questions_quizquestion_question_and_more'),
        ('shared_models', '0007_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
