# Generated by Django 4.0.6 on 2022-07-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0008_alter_question_topics_topicstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
