# Generated by Django 4.0.6 on 2023-01-14 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_rename_questions_quizquestion_question_and_more'),
        ('shared_models', '0009_alter_questionresponse_selected_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('user', 'question', 'quiz')},
        ),
    ]
