# Generated by Django 4.0.6 on 2023-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0010_alter_questionresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
