# Generated by Django 4.0.6 on 2022-07-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0010_quizstatistics_subject_quizstatistics_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='quizzes_completed',
        ),
    ]
