# Generated by Django 4.0.6 on 2022-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0011_remove_userstatistics_quizzes_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
