# Generated by Django 4.0.6 on 2022-11-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_initial'),
        ('shared_models', '0012_question_is_verified'),
    ]

    operations = [
    ]
