version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: documentation/requirements.txt

mkdocs:
  configuration: documentation/mkdocs.yml
  fail_on_warning: false
