version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: elucidate_server
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8081:8081
    volumes:
      - ./server:/app_code
    stdin_open: true # docker run -i
    tty: true # docker run -t
