version: "3.3"

services:
  docs:
    build:
      context: .
      dockerfile: docker/docs/Dockerfile
    container_name: elucidate_docs
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./documentation:/documentation
