# Generated by Django 4.0.5 on 2022-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='author',
        ),
    ]
