# Generated by Django 4.0.6 on 2022-11-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(to='shared_models.question')),
                ('topic', models.ManyToManyField(to='shared_models.topic')),
            ],
        ),
    ]
