# Generated by Django 4.0.6 on 2023-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_questions_quizquestion_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
