# Generated by Django 4.0.6 on 2022-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_create', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_details',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quiz_details',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='quiz_details',
            name='tags',
        ),
        migrations.AddField(
            model_name='quiz_objective',
            name='quiz_details',
            field=models.ManyToManyField(to='quiz_create.quiz_details'),
        ),
        migrations.AddField(
            model_name='quiz_tag',
            name='quiz_details',
            field=models.ManyToManyField(to='quiz_create.quiz_details'),
        ),
    ]
