# Generated by Django 4.0.6 on 2022-07-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_create", "0004_remove_question_answer_answer_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz_objective",
            name="quiz_details",
        ),
        migrations.RemoveField(
            model_name="quiz_question",
            name="is_multichoice",
        ),
        migrations.RemoveField(
            model_name="quiz_question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quiz_tag",
            name="quiz_details",
        ),
        migrations.AddField(
            model_name="quiz_question",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz_question",
            name="question_type",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="quiz_tag",
            name="question",
            field=models.ManyToManyField(to="quiz_create.quiz_question"),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="answer",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="quiz_question",
            name="question",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Quiz_Details",
        ),
        migrations.DeleteModel(
            name="Quiz_Objective",
        ),
    ]
