# Generated by Django 4.0.6 on 2022-07-19 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_create", "0006_rename_quiz_tag_question_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question_tag",
            name="question",
        ),
        migrations.DeleteModel(
            name="Question_Answer",
        ),
        migrations.DeleteModel(
            name="Question_Tag",
        ),
        migrations.DeleteModel(
            name="Quiz_Question",
        ),
    ]
