# Generated by Django 4.0.6 on 2022-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(max_length=5),
        ),
    ]
