site_name: Elucidate Documentation
copyright: Copyright Coders for Causes
repo_url: https://github.com/codersforcauses/elucidate

theme:
  name: "readthedocs"

plugins:
  - search

dev_addr: 0.0.0.0:8000
